tarot_cards = [
    {
        "name": "0 The Fool",
        "number": 0,
        "arcana": "Major",
        "description": "Represents new beginnings, innocence, and a free spirit.",
        "picture": "the_fool.jpg",
        "card": "0 The Fool",
        "crowley_name": "The Fool",
        "upright": "Beginnings, innocence, spontaneity, free spirit",
        "reversed": "Recklessness, poor judgment, hesitation, risk-taking",
        "crowley_upright": "Pure potential, divine madness, the unformed self",
        "crowley_reversed": "Folly, mania, dissipation, wasted potential",
        "numerology": 0,
        "astrology": "Uranus (modern) / Air (element)",
        "element": "Air",
        "hebrew_letter": "Aleph",
        "qabalistic_path": "Path 11 (Kether to Chokmah)",
        "thoth_attributes": {
            "color": "Pale yellow",
            "gemstone": "Topaz",
            "magical_weapon": "The Wand",
            "divine_name": "Parzival",
            "thelemic_title": "The Spirit of Aether",
        },
        "picture_reversed": "the_fool_reversed.jpg",
    },
    {
        "name": "I The Magician",
        "number": 1,
        "arcana": "Major",
        "description": "Symbolizes willpower, creation, and manifestation.",
        "picture": "the_magician.jpg",
        "card": "I The Magician",
        "crowley_name": "The Magus",
        "upright": "Willpower, skill, manifestation, resourcefulness",
        "reversed": "Manipulation, trickery, untapped talents, poor planning",
        "crowley_upright": "Theurgic magic, divine will in action, Mercury",
        "crowley_reversed": "Black magic, deception, misuse of power",
        "numerology": 1,
        "astrology": "Mercury",
        "element": "Air",
        "hebrew_letter": "Beth",
        "qabalistic_path": "Path 12 (Kether to Binah)",
        "thoth_attributes": {
            "color": "Yellow",
            "gemstone": "Agate",
            "magical_weapon": "The Caduceus",
            "divine_name": "Hermes",
            "thelemic_title": "The Magus of Power",
        },
        "picture_reversed": "the_magician_reversed.jpg",
    },
    {
        "name": "II The High Priestess",
        "number": 2,
        "arcana": "Major",
        "description": "Represents intuition, mystery, and the subconscious mind.",
        "picture": "the_high_priestess.jpg",
        "card": "II The High Priestess",
        "crowley_name": "The Priestess",
        "upright": "Intuition, mystery, subconscious, divine feminine",
        "reversed": "Secrets, hidden agendas, repressed intuition, confusion",
        "crowley_upright": "Isis unveiled, lunar wisdom, akashic records",
        "crowley_reversed": "Occult secrecy, dogmatism, blocked intuition",
        "numerology": 2,
        "astrology": "Moon",
        "element": "Water",
        "hebrew_letter": "Gimel",
        "qabalistic_path": "Path 13 (Kether to Tiphareth)",
        "thoth_attributes": {
            "color": "Blue",
            "gemstone": "Moonstone",
            "magical_weapon": "The Bow",
            "divine_name": "Diana",
            "thelemic_title": "The Priestess of the Silver Star",
        },
        "picture_reversed": "the_high_priestess_reversed.jpg",
    },
    {
        "name": "III The Empress",
        "number": 3,
        "arcana": "Major",
        "description": "Symbolizes fertility, abundance, and nurturing.",
        "picture": "the_empress.jpg",
        "card": "III The Empress",
        "crowley_name": "The Empress",
        "upright": "Fertility, femininity, abundance, nature",
        "reversed": "Dependence, smothering, neglect, creative block",
        "crowley_upright": "Venusian creativity, sacred marriage, fecundity",
        "crowley_reversed": "Creative block, emotional stagnation",
        "numerology": 3,
        "astrology": "Venus",
        "element": "Earth",
        "hebrew_letter": "Daleth",
        "qabalistic_path": "Path 14 (Chokmah to Binah)",
        "thoth_attributes": {
            "color": "Emerald green",
            "gemstone": "Emerald",
            "magical_weapon": "The Sceptre",
            "divine_name": "Aphrodite",
            "thelemic_title": "The Daughter of the Mighty Ones",
        },
        "picture_reversed": "the_empress_reversed.jpg",
    },
    {
        "name": "IV The Emperor",
        "number": 4,
        "arcana": "Major",
        "description": "Represents authority, structure, and stability.",
        "picture": "the_emperor.jpg",
        "card": "IV The Emperor",
        "crowley_name": "The Emperor",
        "upright": "Authority, structure, leadership, foundation",
        "reversed": "Tyranny, rigidity, excessive control, immaturity",
        "crowley_upright": "Solar-phallic energy, the conquering hero",
        "crowley_reversed": "Domination, misuse of authority",
        "numerology": 4,
        "astrology": "Aries",
        "element": "Fire",
        "hebrew_letter": "Heh",
        "qabalistic_path": "Path 15 (Chokmah to Tiphareth)",
        "thoth_attributes": {
            "color": "Scarlet",
            "gemstone": "Ruby",
            "magical_weapon": "The Crown",
            "divine_name": "Amoun-Ra",
            "thelemic_title": "The Sun of the Morning",
        },
        "picture_reversed": "the_emperor_reversed.jpg",
    },
    {
        "name": "V The Hierophant",
        "number": 5,
        "arcana": "Major",
        "description": "Symbolizes tradition, conformity, and spiritual wisdom.",
        "picture": "the_hierophant.jpg",
        "card": "V The Hierophant",
        "crowley_name": "The Hierophant (or The Magus of the Eternal)",
        "upright": "Tradition, religion, conformity, education",
        "reversed": "Rebellion, unconventional beliefs, restriction",
        "crowley_upright": "Initiation, the Bull of Heaven (Taurus)",
        "crowley_reversed": "Dogma, blind faith, spiritual tyranny",
        "numerology": 5,
        "astrology": "Taurus",
        "element": "Earth",
        "hebrew_letter": "Vav",
        "qabalistic_path": "Path 16 (Chokmah to Chesed)",
        "thoth_attributes": {
            "color": "Red-orange",
            "gemstone": "Carnelian",
            "magical_weapon": "The Grip",
            "divine_name": "Mithras",
            "thelemic_title": "The Magus of the Eternal Gods",
        },
        "picture_reversed": "the_hierophant_reversed.jpg",
    },
    {
        "name": "VI The Lovers",
        "number": 6,
        "arcana": "Major",
        "description": "Represents love, harmony, and relationships.",
        "picture": "the_lovers.jpg",
        "card": "VI The Lovers",
        "crowley_name": "The Lovers",
        "upright": "Love, harmony, relationships, choices",
        "reversed": "Imbalance, misalignment, disharmony, poor choices",
        "crowley_upright": "Sacred marriage, duality resolved, Gemini",
        "crowley_reversed": "Disharmony, failed union",
        "numerology": 6,
        "astrology": "Gemini",
        "element": "Air",
        "hebrew_letter": "Zain",
        "qabalistic_path": "Path 17 (Binah to Tiphareth)",
        "thoth_attributes": {
            "color": "Orange",
            "gemstone": "Beryl",
            "magical_weapon": "The Lamen",
            "divine_name": "Aphrodite",
            "thelemic_title": "The Children of the Voice Divine",
        },
        "picture_reversed": "the_lovers_reversed.jpg",
    },
    {
        "name": "VII The Chariot",
        "number": 7,
        "arcana": "Major",
        "description": "Symbolizes determination, willpower, and triumph.",
        "picture": "the_chariot.jpg",
        "card": "VII The Chariot",
        "crowley_name": "The Chariot",
        "upright": "Willpower, determination, victory, self-control",
        "reversed": "Lack of direction, aggression, opposition, no control",
        "crowley_upright": "Triumph of the will, Cancerian vehicle",
        "crowley_reversed": "Energy scattered, lack of focus",
        "numerology": 7,
        "astrology": "Cancer",
        "element": "Water",
        "hebrew_letter": "Cheth",
        "qabalistic_path": "Path 18 (Binah to Geburah)",
        "thoth_attributes": {
            "color": "Silver",
            "gemstone": "Pearl",
            "magical_weapon": "The Chariot",
            "divine_name": "Diana",
            "thelemic_title": "The Child of the Powers of the Waters",
        },
        "picture_reversed": "the_chariot_reversed.jpg",
    },
    {
        "name": "VIII Strength",
        "number": 8,
        "arcana": "Major",
        "description": "Represents courage, inner strength, and compassion.",
        "picture": "strength.jpg",
        "card": "VIII Strength",
        "crowley_name": "Lust (formerly Strength)",
        "upright": "Inner strength, courage, compassion, influence",
        "reversed": "Self-doubt, weakness, insecurity, raw emotion",
        "crowley_upright": "Creative energy, the Beast and Babalon, Leo",
        "crowley_reversed": "Brute force, uncontrolled passions",
        "numerology": 8,
        "astrology": "Leo",
        "element": "Fire",
        "hebrew_letter": "Teth",
        "qabalistic_path": "Path 19 (Chesed to Geburah)",
        "thoth_attributes": {
            "color": "Gold",
            "gemstone": "Amber",
            "magical_weapon": "The Whip",
            "divine_name": "Bacchus",
            "thelemic_title": "The Lust of the Lion-Lord",
        },
        "picture_reversed": "strength_reversed.jpg",
    },
    {
        "name": "IX The Hermit",
        "number": 9,
        "arcana": "Major",
        "description": "Symbolizes introspection, wisdom, and solitude.",
        "picture": "the_hermit.jpg",
        "card": "IX The Hermit",
        "crowley_name": "The Hermit",
        "upright": "Soul-searching, introspection, guidance, solitude",
        "reversed": "Isolation, loneliness, withdrawal, ignoring guidance",
        "crowley_upright": "The Light-bearer, Virgoan wisdom",
        "crowley_reversed": "Excessive isolation, misguidance",
        "numerology": 9,
        "astrology": "Virgo",
        "element": "Earth",
        "hebrew_letter": "Yod",
        "qabalistic_path": "Path 20 (Chesed to Tiphareth)",
        "thoth_attributes": {
            "color": "Green-yellow",
            "gemstone": "Peridot",
            "magical_weapon": "The Lamp",
            "divine_name": "Mercury",
            "thelemic_title": "The Magus of the Voice of Light",
        },
        "picture_reversed": "the_hermit_reversed.jpg",
    },
    {
        "name": "X Wheel of Fortune",
        "number": 10,
        "arcana": "Major",
        "description": "Represents change, cycles, and fate.",
        "picture": "wheel_of_fortune.jpg",
        "card": "X Wheel of Fortune",
        "crowley_name": "Fortune",
        "upright": "Change, cycles, destiny, turning point",
        "reversed": "Bad luck, resistance to change, lack of control",
        "crowley_upright": "Jupiterian expansion, karmic cycles",
        "crowley_reversed": "Resistance to change, bad timing",
        "numerology": 10,
        "astrology": "Jupiter",
        "element": "Fire",
        "hebrew_letter": "Kaph",
        "qabalistic_path": "Path 21 (Chesed to Netzach)",
        "thoth_attributes": {
            "color": "Violet",
            "gemstone": "Amethyst",
            "magical_weapon": "The Wheel",
            "divine_name": "Zeus",
            "thelemic_title": "The Lord of the Forces of Life",
        },
        "picture_reversed": "wheel_of_fortune_reversed.jpg",
    },
    {
        "name": "XI Justice",
        "number": 11,
        "arcana": "Major",
        "description": "Symbolizes fairness, truth, and law.",
        "picture": "justice.jpg",
        "card": "XI Justice",
        "crowley_name": "Adjustment (formerly Justice)",
        "upright": "Justice, fairness, truth, cause and effect",
        "reversed": "Unfairness, dishonesty, imbalance, corruption",
        "crowley_upright": "Divine balance, karma, Libra",
        "crowley_reversed": "Injustice, imbalance, denial of truth",
        "numerology": 11,
        "astrology": "Libra",
        "element": "Air",
        "hebrew_letter": "Lamed",
        "qabalistic_path": "Path 22 (Geburah to Tiphareth)",
        "thoth_attributes": {
            "color": "Pale green",
            "gemstone": "Jade",
            "magical_weapon": "The Scales",
            "divine_name": "Themis",
            "thelemic_title": "The Daughter of the Lords of Truth",
        },
        "picture_reversed": "justice_reversed.jpg",
    },
    {
        "name": "XII The Hanged Man",
        "number": 12,
        "arcana": "Major",
        "description": "Represents surrender, new perspectives, and suspension.",
        "picture": "the_hanged_man.jpg",
        "card": "XII The Hanged Man",
        "crowley_name": "The Hanged Man (or The Spirit of the Mighty Waters)",
        "upright": "Sacrifice, new perspective, surrender, pause",
        "reversed": "Stalling, resistance, wasted effort, selfishness",
        "crowley_upright": "Sacrificial gestation, Neptune/Poseidon",
        "crowley_reversed": "False martyrdom, wasted sacrifice",
        "numerology": 12,
        "astrology": "Neptune (modern) / Water (element)",
        "element": "Water",
        "hebrew_letter": "Mem",
        "qabalistic_path": "Path 23 (Geburah to Hod)",
        "thoth_attributes": {
            "color": "Deep blue",
            "gemstone": "Aquamarine",
            "magical_weapon": "The Cup",
            "divine_name": "Osiris",
            "thelemic_title": "The Spirit of the Mighty Waters",
        },
        "picture_reversed": "the_hanged_man_reversed.jpg",
    },
    {
        "name": "XIII Death",
        "number": 13,
        "arcana": "Major",
        "description": "Symbolizes transformation, endings, and new beginnings.",
        "picture": "death.jpg",
        "card": "XIII Death",
        "crowley_name": "Death",
        "upright": "Transformation, endings, change, transition",
        "reversed": "Resistance to change, stagnation, fear of change",
        "crowley_upright": "Scorpionic transformation, alchemical putrefaction",
        "crowley_reversed": "Stagnation, fear of change",
        "numerology": 13,
        "astrology": "Scorpio",
        "element": "Water",
        "hebrew_letter": "Nun",
        "qabalistic_path": "Path 24 (Tiphareth to Netzach)",
        "thoth_attributes": {
            "color": "Black-green",
            "gemstone": "Obsidian",
            "magical_weapon": "The Scythe",
            "divine_name": "Apophis",
            "thelemic_title": "The Child of the Great Transformers",
        },
        "picture_reversed": "death_reversed.jpg",
    },
    {
        "name": "XIV Temperance",
        "number": 14,
        "arcana": "Major",
        "description": "Represents balance, moderation, and harmony.",
        "picture": "temperance.jpg",
        "card": "XIV Temperance",
        "crowley_name": "Art (formerly Temperance)",
        "upright": "Balance, moderation, patience, purpose",
        "reversed": "Imbalance, excess, lack of harmony, recklessness",
        "crowley_upright": "Alchemical marriage, Sagittarian aspiration",
        "crowley_reversed": "Failed alchemy, imbalance",
        "numerology": 14,
        "astrology": "Sagittarius",
        "element": "Fire",
        "hebrew_letter": "Samekh",
        "qabalistic_path": "Path 25 (Tiphareth to Yesod)",
        "thoth_attributes": {
            "color": "Blue-green",
            "gemstone": "Turquoise",
            "magical_weapon": "The Arrow",
            "divine_name": "Chiron",
            "thelemic_title": "The Daughter of the Reconcilers",
        },
        "picture_reversed": "temperance_reversed.jpg",
    },
    {
        "name": "XV The Devil",
        "number": 15,
        "arcana": "Major",
        "description": "Symbolizes bondage, materialism, and negative patterns.",
        "picture": "the_devil.jpg",
        "card": "XV The Devil",
        "crowley_name": "The Devil (Capricorn)",
        "upright": "Addiction, materialism, bondage, shadow self",
        "reversed": "Freedom, release, reclaiming power, detachment",
        "crowley_upright": "Creative energy, Pan, sacred sexuality",
        "crowley_reversed": "Degeneration, material obsession, blindness",
        "numerology": 15,
        "astrology": "Capricorn",
        "element": "Earth",
        "hebrew_letter": "Ayin",
        "qabalistic_path": "Path 26 (Tiphareth to Hod)",
        "thoth_attributes": {
            "color": "Indigo",
            "gemstone": "Onyx",
            "magical_weapon": "The Lamp",
            "divine_name": "Pan",
            "thelemic_title": "The Lord of the Gates of Matter",
        },
        "picture_reversed": "the_devil_reversed.jpg",
    },
    {
        "name": "XVI The Tower",
        "number": 16,
        "arcana": "Major",
        "description": "Represents sudden change, upheaval, and revelation.",
        "picture": "the_tower.jpg",
        "card": "XVI The Tower",
        "crowley_name": "The Tower",
        "upright": "Sudden change, upheaval, revelation, awakening",
        "reversed": "Avoiding disaster, resisting change, fear of upheaval",
        "crowley_upright": "Divine lightning, Mars, destruction of illusion",
        "crowley_reversed": "Avoided disaster, temporary reprieve",
        "numerology": 16,
        "astrology": "Mars",
        "element": "Fire",
        "hebrew_letter": "Pe",
        "qabalistic_path": "Path 27 (Netzach to Hod)",
        "thoth_attributes": {
            "color": "Red",
            "gemstone": "Garnet",
            "magical_weapon": "The Hammer",
            "divine_name": "Thor",
            "thelemic_title": "The Lord of the Hosts of the Mighty",
        },
        "picture_reversed": "the_tower_reversed.jpg",
    },
    {
        "name": "XVII The Star",
        "number": 17,
        "arcana": "Major",
        "description": "Symbolizes hope, inspiration, and serenity.",
        "picture": "the_star.jpg",
        "card": "XVII The Star",
        "crowley_name": "The Star",
        "upright": "Hope, inspiration, serenity, faith",
        "reversed": "Discouragement, hopelessness, insecurity, lack of faith",
        "crowley_upright": "Aquarian vision, Sirius, cosmic wisdom",
        "crowley_reversed": "False hope, delusion",
        "numerology": 17,
        "astrology": "Aquarius",
        "element": "Air",
        "hebrew_letter": "Tzaddi",
        "qabalistic_path": "Path 28 (Netzach to Yesod)",
        "thoth_attributes": {
            "color": "Sky blue",
            "gemstone": "Sapphire",
            "magical_weapon": "The Star",
            "divine_name": "Nuit",
            "thelemic_title": "The Daughter of the Firmament",
        },
        "picture_reversed": "the_star_reversed.jpg",
    },
    {
        "name": "XVIII The Moon",
        "number": 18,
        "arcana": "Major",
        "description": "Represents illusion, intuition, and the subconscious.",
        "picture": "the_moon.jpg",
        "card": "XVIII The Moon",
        "crowley_name": "The Moon",
        "upright": "Illusion, intuition, subconscious, confusion",
        "reversed": "Deception, fear, misunderstanding, clarity",
        "crowley_upright": "Piscean depths, the unconscious, dreams",
        "crowley_reversed": "Nightmares, psychic attack",
        "numerology": 18,
        "astrology": "Pisces",
        "element": "Water",
        "hebrew_letter": "Qoph",
        "qabalistic_path": "Path 29 (Netzach to Malkuth)",
        "thoth_attributes": {
            "color": "Violet-blue",
            "gemstone": "Opal",
            "magical_weapon": "The Mirror",
            "divine_name": "Hecate",
            "thelemic_title": "The Ruler of Flux and Reflux",
        },
        "picture_reversed": "the_moon_reversed.jpg",
    },
    {
        "name": "XIX The Sun",
        "number": 19,
        "arcana": "Major",
        "description": "Symbolizes joy, success, and vitality.",
        "picture": "the_sun.jpg",
        "card": "XIX The Sun",
        "crowley_name": "The Sun",
        "upright": "Joy, success, celebration, positivity",
        "reversed": "Temporary depression, lack of success, negativity",
        "crowley_upright": "Solar consciousness, divine child, enlightenment",
        "crowley_reversed": "Ego inflation, false light",
        "numerology": 19,
        "astrology": "Sun",
        "element": "Fire",
        "hebrew_letter": "Resh",
        "qabalistic_path": "Path 30 (Hod to Yesod)",
        "thoth_attributes": {
            "color": "Gold",
            "gemstone": "Diamond",
            "magical_weapon": "The Disk",
            "divine_name": "Ra",
            "thelemic_title": "The Lord of the Fire of the World",
        },
        "picture_reversed": "the_sun_reversed.jpg",
    },
    {
        "name": "XX Judgment",
        "number": 20,
        "arcana": "Major",
        "description": "Represents awakening, renewal, and inner calling.",
        "picture": "judgement.jpg",
        "picture_reversed": "judgement_reversed.jpg",
        "crowley_name": "The Aeon (formerly Judgment)",
        "upright": "Judgment, rebirth, inner calling, absolution",
        "reversed": "Self-doubt, lack of self-awareness, ignoring the call",
        "crowley_upright": "New Aeon of Horus, cosmic awakening",
        "crowley_reversed": "Fear of change, clinging to old forms",
        "numerology": 20,
        "astrology": "Pluto (modern) / Fire (element)",
        "element": "Fire",
        "hebrew_letter": "Shin",
        "qabalistic_path": "Path 31 (Hod to Malkuth)",
        "thoth_attributes": {
          "color": "Orange-red",
          "gemstone": "Ruby",
          "magical_weapon": "The Trumpet",
          "divine_name": "Horus",
          "thelemic_title": "The Spirit of the Primal Fire"
        }
    },
    {
        "name": "XXI The World",
        "number": 21,
        "arcana": "Major",
        "description": "Symbolizes completion, integration, and accomplishment.",
        "picture": "the_world.jpg",
        "card": "XXI The World",
        "crowley_name": "The Universe",
        "upright": "Completion, integration, accomplishment, travel",
        "reversed": "Lack of completion, lack of closure, needing more time",
        "crowley_upright": "Saturnian completion, the Great Work fulfilled",
        "crowley_reversed": "Incomplete work, delay of fulfillment",
        "numerology": 21,
        "astrology": "Saturn",
        "element": "Earth",
        "hebrew_letter": "Tau",
        "qabalistic_path": "Path 32 (Yesod to Malkuth)",
        "thoth_attributes": {
            "color": "Indigo",
            "gemstone": "Jet",
            "magical_weapon": "The Ankh",
            "divine_name": "Saturn",
            "thelemic_title": "The Great One of the Night of Time",
        },
        "picture_reversed": "the_world_reversed.jpg",
    },
    {
        "name": "Ace of Cups",
        "number": 22,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Represents new emotional beginnings, love, and intuition.",
        "picture": "ace_of_cups.jpg",
        "card": "Ace of Cups",
        "crowley_name": "The Root of the Powers of Water",
        "upright": "New feelings, spirituality, intuition, love",
        "reversed": "Emotional loss, blocked creativity, emptiness",
        "crowley_upright": "Grail consciousness, divine love",
        "crowley_reversed": "Emotional blockage, corrupted love",
        "numerology": 1,
        "thoth_attributes": {
            "color": "Blue",
            "planet": "Moon in Cancer",
            "thelemic_key": "The Womb of the World",
        },
        "picture_reversed": "ace_of_cups_reversed.jpg",
    },
    {
        "name": "Two of Cups",
        "number": 23,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Symbolizes partnership, unity, and mutual attraction.",
        "picture": "2_of_cups.jpg",
        "card": "Two of Cups",
        "crowley_name": "Love",
        "upright": "Unity, partnership, mutual attraction, connection",
        "reversed": "Imbalance, broken communication, tension, separation",
        "crowley_upright": "Venus in Cancer - Sacred marriage",
        "crowley_reversed": "Disharmony, failed union",
        "numerology": 2,
        "thoth_attributes": {
            "color": "Blue-green",
            "planet": "Venus in Cancer",
            "thelemic_key": "The Chalice of Ecstasy",
        },
        "picture_reversed": "2_of_cups_reversed.jpg",
    },
    {
        "name": "Three of Cups",
        "number": 24,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Represents celebration, friendship, and community.",
        "picture": "3_of_cups.jpg",
        "card": "Three of Cups",
        "crowley_name": "Abundance",
        "upright": "Celebration, friendship, community, joy",
        "reversed": "Overindulgence, gossip, isolation, conflict",
        "crowley_upright": "Mercury in Cancer - Emotional abundance",
        "crowley_reversed": "Emotional excess",
        "numerology": 3,
        "thoth_attributes": {
            "color": "Blue-silver",
            "planet": "Mercury in Cancer",
            "thelemic_key": "The Waters of Life",
        },
        "picture_reversed": "3_of_cups_reversed.jpg",
    },
    {
        "name": "Four of Cups",
        "number": 25,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Symbolizes apathy, contemplation, and reevaluation.",
        "picture": "4_of_cups.jpg",
        "card": "Four of Cups",
        "crowley_name": "Luxury",
        "upright": "Apathy, contemplation, disconnection, missed opportunities",
        "reversed": "New opportunities, awareness, acceptance, engagement",
        "crowley_upright": "Moon in Scorpio - Emotional depth",
        "crowley_reversed": "Emotional stagnation",
        "numerology": 4,
        "thoth_attributes": {
            "color": "Deep blue",
            "planet": "Moon in Scorpio",
            "thelemic_key": "The Well of the Unconscious",
        },
        "picture_reversed": "4_of_cups_reversed.jpg",
    },
    {
        "name": "Five of Cups",
        "number": 26,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Represents loss, regret, and disappointment.",
        "picture": "5_of_cups.jpg",
        "card": "Five of Cups",
        "crowley_name": "Disappointment",
        "upright": "Loss, grief, disappointment, regret",
        "reversed": "Acceptance, moving on, finding peace, personal growth",
        "crowley_upright": "Mars in Scorpio - Emotional trial",
        "crowley_reversed": "Release from sorrow",
        "numerology": 5,
        "thoth_attributes": {
            "color": "Blue-black",
            "planet": "Mars in Scorpio",
            "thelemic_key": "The Waters of Bitterness",
        },
        "picture_reversed": "5_of_cups_reversed.jpg",
    },
    {
        "name": "Six of Cups",
        "number": 27,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Symbolizes nostalgia, childhood memories, and innocence.",
        "picture": "6_of_cups.jpg",
        "card": "Six of Cups",
        "crowley_name": "Pleasure",
        "upright": "Nostalgia, childhood, memories, innocence",
        "reversed": "Living in the past, moving forward, letting go",
        "crowley_upright": "Sun in Scorpio - Emotional alchemy",
        "crowley_reversed": "Nostalgic obsession",
        "numerology": 6,
        "thoth_attributes": {
            "color": "Gold-blue",
            "planet": "Sun in Scorpio",
            "thelemic_key": "The Alchemical Marriage",
        },
        "picture_reversed": "6_of_cups_reversed.jpg",
    },
    {
        "name": "Seven of Cups",
        "number": 28,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Represents choices, illusions, and wishful thinking.",
        "picture": "7_of_cups.jpg",
        "card": "Seven of Cups",
        "crowley_name": "Debauch",
        "upright": "Choices, illusions, wishful thinking, options",
        "reversed": "Clarity, decision-making, focus, reality check",
        "crowley_upright": "Venus in Scorpio - Emotional intoxication",
        "crowley_reversed": "Sobriety of vision",
        "numerology": 7,
        "thoth_attributes": {
            "color": "Violet-blue",
            "planet": "Venus in Scorpio",
            "thelemic_key": "The Chalice of Delusion",
        },
        "picture_reversed": "7_of_cups_reversed.jpg",
    },
    {
        "name": "Eight of Cups",
        "number": 29,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Symbolizes walking away, abandonment, and seeking deeper meaning.",
        "picture": "8_of_cups.jpg",
        "card": "Eight of Cups",
        "crowley_name": "Indolence",
        "upright": "Walking away, abandonment, leaving behind, seeking truth",
        "reversed": "Avoidance, fear of change, staying in bad situation",
        "crowley_upright": "Saturn in Pisces - Emotional withdrawal",
        "crowley_reversed": "Spiritual laziness",
        "numerology": 8,
        "thoth_attributes": {
            "color": "Gray-blue",
            "planet": "Saturn in Pisces",
            "thelemic_key": "The Waters of Stagnation",
        },
        "picture_reversed": "8_of_cups_reversed.jpg",
    },
    {
        "name": "Nine of Cups",
        "number": 30,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Represents satisfaction, emotional fulfillment, and wishes come true.",
        "picture": "9_of_cups.jpg",
        "card": "Nine of Cups",
        "crowley_name": "Happiness",
        "upright": "Wishes fulfilled, comfort, satisfaction, contentment",
        "reversed": "Smugness, dissatisfaction, materialism, unfulfilled desires",
        "crowley_upright": "Jupiter in Pisces - Emotional fulfillment",
        "crowley_reversed": "False contentment",
        "numerology": 9,
        "thoth_attributes": {
            "color": "Blue-violet",
            "planet": "Jupiter in Pisces",
            "thelemic_key": "The Chalice of Bliss",
        },
        "picture_reversed": "9_of_cups_reversed.jpg",
    },
    {
        "name": "Ten of Cups",
        "number": 31,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Symbolizes happiness, harmony, and emotional fulfillment.",
        "picture": "10_of_cups.jpg",
        "card": "Ten of Cups",
        "crowley_name": "Satiety",
        "upright": "Harmony, happiness, family, joy, alignment",
        "reversed": "Disharmony, broken home, misalignment, conflict",
        "crowley_upright": "Mars in Pisces - Emotional completion",
        "crowley_reversed": "Emotional excess",
        "numerology": 10,
        "thoth_attributes": {
            "color": "Blue-indigo",
            "planet": "Mars in Pisces",
            "thelemic_key": "The Waters of Perfect Peace",
        },
        "picture_reversed": "10_of_cups_reversed.jpg",
    },
    {
        "name": "Page of Cups",
        "number": 32,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Represents creativity, emotional messages, and new opportunities.",
        "picture": "page_of_cups.jpg",
        "card": "Page of Cups",
        "crowley_name": "The Princess of the Waters",
        "upright": "Creative opportunities, intuitive messages, curiosity",
        "reversed": "Emotional immaturity, creative block, insecurity",
        "crowley_upright": "Earth of Water - New emotional beginnings",
        "crowley_reversed": "Emotional instability",
        "numerology": None,
        "thoth_attributes": {
            "element": "Earth of Water",
            "thelemic_key": "The Lotus Rising",
        },
        "picture_reversed": "page_of_cups_reversed.jpg",
    },
    {
        "name": "Knight of Cups",
        "number": 33,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Symbolizes romance, charm, and emotional pursuits.",
        "picture": "knight_of_cups.jpg",
        "card": "Knight of Cups",
        "crowley_name": "The Lord of the Waves and the Waters",
        "upright": "Romance, charm, imagination, emotion",
        "reversed": "Moodiness, disappointment, unrealistic expectations",
        "crowley_upright": "Fire of Water - Passionate emotions",
        "crowley_reversed": "Emotional turbulence",
        "numerology": None,
        "thoth_attributes": {
            "element": "Fire of Water",
            "thelemic_key": "The Tidal Wave",
        },
        "picture_reversed": "knight_of_cups_reversed.jpg",
    },
    {
        "name": "Queen of Cups",
        "number": 34,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Represents compassion, emotional balance, and intuition.",
        "picture": "queen_of_cups.jpg",
        "card": "Queen of Cups",
        "crowley_name": "The Queen of the Thrones of the Waters",
        "upright": "Compassion, emotional stability, intuition, nurturing",
        "reversed": "Emotional instability, insecurity, dependence",
        "crowley_upright": "Water of Water - Pure intuition",
        "crowley_reversed": "Emotional manipulation",
        "numerology": None,
        "thoth_attributes": {
            "element": "Water of Water",
            "thelemic_key": "The Grail Queen",
        },
        "picture_reversed": "queen_of_cups_reversed.jpg",
    },
    {
        "name": "King of Cups",
        "number": 35,
        "arcana": "Minor",
        "suit": "Cups",
        "description": "Symbolizes emotional control, diplomacy, and wisdom.",
        "picture": "king_of_cups.jpg",
        "card": "King of Cups",
        "crowley_name": "The Prince of the Chariot of the Waters",
        "upright": "Emotional balance, diplomacy, control, compassion",
        "reversed": "Emotional manipulation, moodiness, volatility",
        "crowley_upright": "Air of Water - Balanced emotions",
        "crowley_reversed": "Cold calculation",
        "numerology": None,
        "thoth_attributes": {
            "element": "Air of Water",
            "thelemic_key": "The Reflecting Mind",
        },
        "picture_reversed": "king_of_cups_reversed.jpg",
    },
    {
        "name": "Ace of Pentacles",
        "number": 36,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Represents new financial opportunities, prosperity, and abundance.",
        "picture": "ace_of_pentacles.jpg",
        "card": "Ace of Pentacles",
        "crowley_name": "The Root of the Powers of Earth",
        "upright": "New opportunities, prosperity, security, abundance",
        "reversed": "Missed chances, lack of planning, bad investment",
        "crowley_upright": "Materialization, the body as temple",
        "crowley_reversed": "Material obsession, greed",
        "numerology": 1,
        "thoth_attributes": {
            "color": "Green",
            "planet": "Saturn in Capricorn",
            "thelemic_key": "The Seed of the World",
        },
        "picture_reversed": "ace_of_pentacles_reversed.jpg",
    },
    {
        "name": "Two of Pentacles",
        "number": 37,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Symbolizes balance, adaptability, and juggling priorities.",
        "picture": "2_of_pentacles.jpg",
        "card": "Two of Pentacles",
        "crowley_name": "Change",
        "upright": "Balance, adaptability, flexibility, juggling priorities",
        "reversed": "Disorganization, financial loss, overwhelmed, imbalance",
        "crowley_upright": "Jupiter in Capricorn - Balanced change",
        "crowley_reversed": "Chaotic change",
        "numerology": 2,
        "thoth_attributes": {
            "color": "Green-blue",
            "planet": "Jupiter in Capricorn",
            "thelemic_key": "The Dance of Life",
        },
        "picture_reversed": "2_of_pentacles_reversed.jpg",
    },
    {
        "name": "Three of Pentacles",
        "number": 38,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Represents teamwork, collaboration, and mastery.",
        "picture": "3_of_pentacles.jpg",
        "card": "Three of Pentacles",
        "crowley_name": "Works",
        "upright": "Teamwork, collaboration, learning, implementation",
        "reversed": "Lack of teamwork, disorganized, poor quality work",
        "crowley_upright": "Mars in Capricorn - Material works",
        "crowley_reversed": "Failed projects",
        "numerology": 3,
        "thoth_attributes": {
            "color": "Green-red",
            "planet": "Mars in Capricorn",
            "thelemic_key": "The Builder's Stone",
        },
        "picture_reversed": "3_of_pentacles_reversed.jpg",
    },
    {
        "name": "Four of Pentacles",
        "number": 39,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Symbolizes stability, security, and control.",
        "picture": "4_of_pentacles.jpg",
        "card": "Four of Pentacles",
        "crowley_name": "Power",
        "upright": "Security, control, saving money, conservatism",
        "reversed": "Greed, materialism, stinginess, possessiveness",
        "crowley_upright": "Sun in Capricorn - Earthly power",
        "crowley_reversed": "Tyrannical control",
        "numerology": 4,
        "thoth_attributes": {
            "color": "Green-gold",
            "planet": "Sun in Capricorn",
            "thelemic_key": "The Fortress",
        },
        "picture_reversed": "4_of_pentacles_reversed.jpg",
    },
    {
        "name": "Five of Pentacles",
        "number": 40,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Represents financial hardship, isolation, and struggle.",
        "picture": "5_of_pentacles.jpg",
        "card": "Five of Pentacles",
        "crowley_name": "Worry",
        "upright": "Financial loss, poverty, isolation, worry",
        "reversed": "Recovery, charity, improvement, new opportunities",
        "crowley_upright": "Mercury in Taurus - Material anxiety",
        "crowley_reversed": "Relief from worry",
        "numerology": 5,
        "thoth_attributes": {
            "color": "Green-brown",
            "planet": "Mercury in Taurus",
            "thelemic_key": "The Shadow of Matter",
        },
        "picture_reversed": "5_of_pentacles_reversed.jpg",
    },
    {
        "name": "Six of Pentacles",
        "number": 41,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Symbolizes generosity, charity, and giving.",
        "picture": "6_of_pentacles.jpg",
        "card": "Six of Pentacles",
        "crowley_name": "Success",
        "upright": "Generosity, charity, sharing, giving and receiving",
        "reversed": "Selfishness, inequality, power dynamics, debt",
        "crowley_upright": "Moon in Taurus - Material success",
        "crowley_reversed": "False generosity",
        "numerology": 6,
        "thoth_attributes": {
            "color": "Green-silver",
            "planet": "Moon in Taurus",
            "thelemic_key": "The Golden Cup",
        },
        "picture_reversed": "6_of_pentacles_reversed.jpg",
    },
    {
        "name": "Seven of Pentacles",
        "number": 42,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Represents patience, long-term vision, and perseverance.",
        "picture": "7_of_pentacles.jpg",
        "card": "Seven of Pentacles",
        "crowley_name": "Failure",
        "upright": "Patience, long-term view, perseverance, investment",
        "reversed": "Lack of results, impatience, wasted effort",
        "crowley_upright": "Saturn in Taurus - Material test",
        "crowley_reversed": "Complete failure",
        "numerology": 7,
        "thoth_attributes": {
            "color": "Green-black",
            "planet": "Saturn in Taurus",
            "thelemic_key": "The Unripe Harvest",
        },
        "picture_reversed": "7_of_pentacles_reversed.jpg",
    },
    {
        "name": "Eight of Pentacles",
        "number": 43,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Symbolizes craftsmanship, dedication, and skill.",
        "picture": "8_of_pentacles.jpg",
        "card": "Eight of Pentacles",
        "crowley_name": "Prudence",
        "upright": "Apprenticeship, craftsmanship, skill development",
        "reversed": "Lack of focus, no motivation, poor quality work",
        "crowley_upright": "Sun in Virgo - Material craftsmanship",
        "crowley_reversed": "Poor workmanship",
        "numerology": 8,
        "thoth_attributes": {
            "color": "Green-yellow",
            "planet": "Sun in Virgo",
            "thelemic_key": "The Skillful Hand",
        },
        "picture_reversed": "8_of_pentacles_reversed.jpg",
    },
    {
        "name": "Nine of Pentacles",
        "number": 44,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Represents financial independence, luxury, and self-sufficiency.",
        "picture": "9_of_pentacles.jpg",
        "card": "Nine of Pentacles",
        "crowley_name": "Gain",
        "upright": "Abundance, luxury, self-sufficiency, financial independence",
        "reversed": "Financial loss, loneliness, overindulgence, dependence",
        "crowley_upright": "Venus in Virgo - Material gain",
        "crowley_reversed": "Material loss",
        "numerology": 9,
        "thoth_attributes": {
            "color": "Green-white",
            "planet": "Venus in Virgo",
            "thelemic_key": "The Garden of Eden",
        },
        "picture_reversed": "9_of_pentacles_reversed.jpg",
    },
    {
        "name": "Ten of Pentacles",
        "number": 45,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Symbolizes wealth, legacy, and family security.",
        "picture": "10_of_pentacles.jpg",
        "card": "Ten of Pentacles",
        "crowley_name": "Wealth",
        "upright": "Wealth, family, legacy, establishment, retirement",
        "reversed": "Financial failure, lack of stability, family conflict",
        "crowley_upright": "Mercury in Virgo - Material completion",
        "crowley_reversed": "Corrupted wealth",
        "numerology": 10,
        "thoth_attributes": {
            "color": "Green-gold",
            "planet": "Mercury in Virgo",
            "thelemic_key": "The Full Corn",
        },
        "picture_reversed": "10_of_pentacles_reversed.jpg",
    },
    {
        "name": "Page of Pentacles",
        "number": 46,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Represents new opportunities, learning, and practicality.",
        "picture": "page_of_pentacles.jpg",
        "card": "Page of Pentacles",
        "crowley_name": "The Princess of the Echoing Hills",
        "upright": "New opportunities, learning, manifestation, potential",
        "reversed": "Lack of progress, procrastination, wasted potential",
        "crowley_upright": "Earth of Earth - New material beginnings",
        "crowley_reversed": "Material stagnation",
        "numerology": None,
        "thoth_attributes": {
            "element": "Earth of Earth",
            "thelemic_key": "The Seed of the Earth",
        },
        "picture_reversed": "page_of_pentacles_reversed.jpg",
    },
    {
        "name": "Knight of Pentacles",
        "number": 47,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Symbolizes diligence, responsibility, and reliability.",
        "picture": "knight_of_pentacles.jpg",
        "card": "Knight of Pentacles",
        "crowley_name": "The Lord of the Wide and Fertile Land",
        "upright": "Hard work, routine, responsibility, diligence",
        "reversed": "Boredom, lack of progress, laziness, procrastination",
        "crowley_upright": "Fire of Earth - Material energy",
        "crowley_reversed": "Stagnant energy",
        "numerology": None,
        "thoth_attributes": {"element": "Fire of Earth", "thelemic_key": "The Plowman"},
        "picture_reversed": "knight_of_pentacles_reversed.jpg",
    },
    {
        "name": "Queen of Pentacles",
        "number": 48,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Represents nurturing, practicality, and financial security.",
        "picture": "queen_of_pentacles.jpg",
        "card": "Queen of Pentacles",
        "crowley_name": "The Queen of the Thrones of Earth",
        "upright": "Nurturing, practical, down-to-earth, financial security",
        "reversed": "Financial insecurity, smothering, materialism",
        "crowley_upright": "Water of Earth - Material fertility",
        "crowley_reversed": "Material obsession",
        "numerology": None,
        "thoth_attributes": {
            "element": "Water of Earth",
            "thelemic_key": "The Earth Mother",
        },
        "picture_reversed": "queen_of_pentacles_reversed.jpg",
    },
    {
        "name": "King of Pentacles",
        "number": 49,
        "arcana": "Minor",
        "suit": "Pentacles",
        "description": "Symbolizes abundance, leadership, and financial success.",
        "picture": "king_of_pentacles.jpg",
        "card": "King of Pentacles",
        "crowley_name": "The Prince of the Chariot of Earth",
        "upright": "Wealth, business, leadership, security, abundance",
        "reversed": "Financial failure, greed, materialism, poor management",
        "crowley_upright": "Air of Earth - Material intellect",
        "crowley_reversed": "Material tyranny",
        "numerology": None,
        "thoth_attributes": {
            "element": "Air of Earth",
            "thelemic_key": "The Architect",
        },
        "picture_reversed": "king_of_pentacles_reversed.jpg",
    },
    {
        "name": "Ace of Swords",
        "number": 50,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Represents mental clarity, breakthroughs, and new ideas.",
        "picture": "ace_of_swords.jpg",
        "card": "Ace of Swords",
        "crowley_name": "The Root of the Powers of Air",
        "upright": "Breakthroughs, new ideas, mental clarity, success",
        "reversed": "Confusion, chaos, lack of clarity, miscommunication",
        "crowley_upright": "Pure intellect, divine truth",
        "crowley_reversed": "Mental tyranny, false knowledge",
        "numerology": 1,
        "thoth_attributes": {
            "color": "Yellow",
            "planet": "Mercury in Libra",
            "thelemic_key": "The Sword of Truth",
        },
        "picture_reversed": "ace_of_swords_reversed.jpg",
    },
    {
        "name": "Two of Swords",
        "number": 51,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Symbolizes indecision, stalemate, and avoidance.",
        "picture": "2_of_swords.jpg",
        "card": "Two of Swords",
        "crowley_name": "Peace",
        "upright": "Indecision, stalemate, difficult choices, avoidance",
        "reversed": "Indecision, confusion, information overload, imbalance",
        "crowley_upright": "Moon in Libra - Balanced thought",
        "crowley_reversed": "False peace",
        "numerology": 2,
        "thoth_attributes": {
            "color": "Pale yellow",
            "planet": "Moon in Libra",
            "thelemic_key": "The Crossed Swords",
        },
        "picture_reversed": "2_of_swords_reversed.jpg",
    },
    {
        "name": "Three of Swords",
        "number": 52,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Represents heartbreak, sorrow, and emotional pain.",
        "picture": "3_of_swords.jpg",
        "card": "Three of Swords",
        "crowley_name": "Sorrow",
        "upright": "Heartbreak, grief, sorrow, rejection",
        "reversed": "Healing, forgiveness, moving on, reconciliation",
        "crowley_upright": "Saturn in Libra - Mental anguish",
        "crowley_reversed": "Release from sorrow",
        "numerology": 3,
        "thoth_attributes": {
            "color": "Gray-yellow",
            "planet": "Saturn in Libra",
            "thelemic_key": "The Pierced Heart",
        },
        "picture_reversed": "3_of_swords_reversed.jpg",
    },
    {
        "name": "Four of Swords",
        "number": 53,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Symbolizes rest, recovery, and contemplation.",
        "picture": "4_of_swords.jpg",
        "card": "Four of Swords",
        "crowley_name": "Truce",
        "upright": "Rest, recovery, contemplation, relaxation",
        "reversed": "Restlessness, burnout, stress, lack of progress",
        "crowley_upright": "Jupiter in Libra - Mental respite",
        "crowley_reversed": "False calm",
        "numerology": 4,
        "thoth_attributes": {
            "color": "Yellow-blue",
            "planet": "Jupiter in Libra",
            "thelemic_key": "The Sword in Repose",
        },
        "picture_reversed": "4_of_swords_reversed.jpg",
    },
    {
        "name": "Five of Swords",
        "number": 54,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Represents conflict, tension, and winning at a cost.",
        "picture": "5_of_swords.jpg",
        "card": "Five of Swords",
        "crowley_name": "Defeat",
        "upright": "Conflict, tension, loss, defeat",
        "reversed": "Reconciliation, resolution, moving on, learning lessons",
        "crowley_upright": "Venus in Aquarius - Intellectual conflict",
        "crowley_reversed": "Lessons learned",
        "numerology": 5,
        "thoth_attributes": {
            "color": "Yellow-green",
            "planet": "Venus in Aquarius",
            "thelemic_key": "The Broken Sword",
        },
        "picture_reversed": "5_of_swords_reversed.jpg",
    },
    {
        "name": "Six of Swords",
        "number": 55,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Symbolizes transition, moving on, and leaving difficulties behind.",
        "picture": "6_of_swords.jpg",
        "card": "Six of Swords",
        "crowley_name": "Science",
        "upright": "Transition, moving on, leaving behind, progress",
        "reversed": "Resistance to change, unresolved issues, emotional baggage",
        "crowley_upright": "Mercury in Aquarius - Intellectual progress",
        "crowley_reversed": "Mental stagnation",
        "numerology": 6,
        "thoth_attributes": {
            "color": "Yellow-violet",
            "planet": "Mercury in Aquarius",
            "thelemic_key": "The Sword of Reason",
        },
        "picture_reversed": "6_of_swords_reversed.jpg",
    },
    {
        "name": "Seven of Swords",
        "number": 56,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Represents deception, strategy, and stealth.",
        "picture": "7_of_swords.jpg",
        "card": "Seven of Swords",
        "crowley_name": "Futility",
        "upright": "Deception, trickery, strategy, secrecy",
        "reversed": "Coming clean, truth revealed, conscience, regret",
        "crowley_upright": "Moon in Aquarius - Mental deception",
        "crowley_reversed": "Truth revealed",
        "numerology": 7,
        "thoth_attributes": {
            "color": "Yellow-gray",
            "planet": "Moon in Aquarius",
            "thelemic_key": "The Unstable Mind",
        },
        "picture_reversed": "7_of_swords_reversed.jpg",
    },
    {
        "name": "Eight of Swords",
        "number": 57,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Symbolizes restriction, self-imposed limitations, and feeling trapped.",
        "picture": "8_of_swords.jpg",
        "card": "Eight of Swords",
        "crowley_name": "Interference",
        "upright": "Restriction, powerlessness, self-victimization, trapped",
        "reversed": "Self-acceptance, new perspective, freedom",
        "crowley_upright": "Jupiter in Gemini - Mental restriction",
        "crowley_reversed": "Breaking free",
        "numerology": 8,
        "thoth_attributes": {
            "color": "Yellow-orange",
            "planet": "Jupiter in Gemini",
            "thelemic_key": "The Web of Thought",
        },
        "picture_reversed": "8_of_swords_reversed.jpg",
    },
    {
        "name": "Nine of Swords",
        "number": 58,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Represents anxiety, worry, and fear.",
        "picture": "9_of_swords.jpg",
        "card": "Nine of Swords",
        "crowley_name": "Cruelty",
        "upright": "Anxiety, worry, fear, nightmares",
        "reversed": "Hope, reaching out, facing fears, healing",
        "crowley_upright": "Mars in Gemini - Mental torment",
        "crowley_reversed": "Release from fear",
        "numerology": 9,
        "thoth_attributes": {
            "color": "Yellow-red",
            "planet": "Mars in Gemini",
            "thelemic_key": "The Sword of Despair",
        },
        "picture_reversed": "9_of_swords_reversed.jpg",
    },
    {
        "name": "Ten of Swords",
        "number": 59,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Symbolizes betrayal, endings, and painful lessons.",
        "picture": "10_of_swords.jpg",
        "card": "Ten of Swords",
        "crowley_name": "Ruin",
        "upright": "Failure, collapse, defeat, crisis",
        "reversed": "Recovery, regeneration, resisting inevitable",
        "crowley_upright": "Sun in Gemini - Mental collapse",
        "crowley_reversed": "New beginnings from ruin",
        "numerology": 10,
        "thoth_attributes": {
            "color": "Yellow-black",
            "planet": "Sun in Gemini",
            "thelemic_key": "The Final Sword",
        },
        "picture_reversed": "10_of_swords_reversed.jpg",
    },
    {
        "name": "Page of Swords",
        "number": 60,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Represents curiosity, new ideas, and intellectual exploration.",
        "picture": "page_of_swords.jpg",
        "card": "Page of Swords",
        "crowley_name": "The Princess of the Rushing Winds",
        "upright": "New ideas, curiosity, communication, vigilance",
        "reversed": "Gossip, haste, lack of planning, deception",
        "crowley_upright": "Earth of Air - New mental beginnings",
        "crowley_reversed": "Mental instability",
        "numerology": None,
        "thoth_attributes": {
            "element": "Earth of Air",
            "thelemic_key": "The Wind's Messenger",
        },
        "picture_reversed": "page_of_swords_reversed.jpg",
    },
    {
        "name": "Knight of Swords",
        "number": 61,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Symbolizes action, ambition, and assertiveness.",
        "picture": "knight_of_swords.jpg",
        "card": "Knight of Swords",
        "crowley_name": "The Lord of the Winds and the Breezes",
        "upright": "Action, ambition, quick thinking, assertiveness",
        "reversed": "Aggression, recklessness, impulsiveness, hostility",
        "crowley_upright": "Fire of Air - Intellectual energy",
        "crowley_reversed": "Destructive thoughts",
        "numerology": None,
        "thoth_attributes": {
            "element": "Fire of Air",
            "thelemic_key": "The Storm Wind",
        },
        "picture_reversed": "knight_of_swords_reversed.jpg",
    },
    {
        "name": "Queen of Swords",
        "number": 62,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Represents clarity, independence, and unbiased judgment.",
        "picture": "queen_of_swords.jpg",
        "card": "Queen of Swords",
        "crowley_name": "The Queen of the Thrones of Air",
        "upright": "Independence, unbiased judgment, clear boundaries",
        "reversed": "Coldness, bitterness, harsh judgment, emotional manipulation",
        "crowley_upright": "Water of Air - Clear thought",
        "crowley_reversed": "Mental cruelty",
        "numerology": None,
        "thoth_attributes": {
            "element": "Water of Air",
            "thelemic_key": "The Clear Mind",
        },
        "picture_reversed": "queen_of_swords_reversed.jpg",
    },
    {
        "name": "King of Swords",
        "number": 63,
        "arcana": "Minor",
        "suit": "Swords",
        "description": "Symbolizes intellect, authority, and clear communication.",
        "picture": "king_of_swords.jpg",
        "card": "King of Swords",
        "crowley_name": "The Prince of the Chariot of the Winds",
        "upright": "Authority, truth, discipline, integrity",
        "reversed": "Manipulation, cruelty, tyranny, abuse of power",
        "crowley_upright": "Air of Air - Pure intellect",
        "crowley_reversed": "Tyrannical mind",
        "numerology": None,
        "thoth_attributes": {
            "element": "Air of Air",
            "thelemic_key": "The Razor's Edge",
        },
        "picture_reversed": "king_of_swords_reversed.jpg",
    },
    {
        "name": "Ace of Wands",
        "number": 64,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Represents inspiration, new opportunities, and creative energy.",
        "picture": "ace_of_wands.jpg",
        "card": "Ace of Wands",
        "crowley_name": "The Root of the Powers of Fire",
        "upright": "Inspiration, new opportunities, growth, potential",
        "reversed": "Delays, lack of motivation, missed opportunities",
        "crowley_upright": "Phallic energy, primal creative force",
        "crowley_reversed": "Energy blocked at root, creative frustration",
        "numerology": 1,
        "thoth_attributes": {
            "color": "Scarlet",
            "planet": "Sun in Aries",
            "thelemic_key": "Energy of the Sun at its most potent",
        },
        "picture_reversed": "ace_of_wands_reversed.jpg",
    },
    {
        "name": "Two of Wands",
        "number": 65,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Symbolizes planning, future goals, and personal power.",
        "picture": "2_of_wands.jpg",
        "card": "Two of Wands",
        "crowley_name": "Dominion",
        "upright": "Planning, discovery, decisions, future plans",
        "reversed": "Bad planning, over-analyzing, lack of action",
        "crowley_upright": "Mars in Aries - Controlled energy",
        "crowley_reversed": "Energy scattered, lack of focus",
        "numerology": 2,
        "thoth_attributes": {
            "color": "Red-orange",
            "planet": "Mars in Aries",
            "thelemic_key": "The Will to Power",
        },
        "picture_reversed": "2_of_wands_reversed.jpg",
    },
    {
        "name": "Three of Wands",
        "number": 66,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Represents expansion, foresight, and exploration.",
        "picture": "3_of_wands.jpg",
        "card": "Three of Wands",
        "crowley_name": "Virtue",
        "upright": "Progress, expansion, foresight, overseas opportunities",
        "reversed": "Obstacles, delays, frustration, lack of progress",
        "crowley_upright": "Sun in Aries - Established strength",
        "crowley_reversed": "Arrogance, overextension",
        "numerology": 3,
        "thoth_attributes": {
            "color": "Gold",
            "planet": "Sun in Aries",
            "thelemic_key": "Established Solar Power",
        },
        "picture_reversed": "3_of_wands_reversed.jpg",
    },
    {
        "name": "Four of Wands",
        "number": 67,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Symbolizes celebration, harmony, and homecoming.",
        "picture": "4_of_wands.jpg",
        "card": "Four of Wands",
        "crowley_name": "Completion",
        "upright": "Celebration, harmony, home, community",
        "reversed": "Lack of support, instability, canceled celebrations",
        "crowley_upright": "Venus in Aries - Harmonious energy",
        "crowley_reversed": "Superficial harmony",
        "numerology": 4,
        "thoth_attributes": {
            "color": "Deep red",
            "planet": "Venus in Aries",
            "thelemic_key": "Perfect Work Perfected",
        },
        "picture_reversed": "4_of_wands_reversed.jpg",
    },
    {
        "name": "Five of Wands",
        "number": 68,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Represents competition, conflict, and rivalry.",
        "picture": "5_of_wands.jpg",
        "card": "Five of Wands",
        "crowley_name": "Strife",
        "upright": "Conflict, competition, disagreements, tension",
        "reversed": "Avoiding conflict, resolution, finding common ground",
        "crowley_upright": "Saturn in Leo - Creative tension",
        "crowley_reversed": "Avoidance of necessary conflict",
        "numerology": 5,
        "thoth_attributes": {
            "color": "Red-black",
            "planet": "Saturn in Leo",
            "thelemic_key": "The Battle for Life",
        },
        "picture_reversed": "5_of_wands_reversed.jpg",
    },
    {
        "name": "Six of Wands",
        "number": 69,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Symbolizes victory, success, and public recognition.",
        "picture": "6_of_wands.jpg",
        "card": "Six of Wands",
        "crowley_name": "Victory",
        "upright": "Victory, success, recognition, progress",
        "reversed": "Egotism, fall from grace, lack of recognition",
        "crowley_upright": "Jupiter in Leo - Triumphant energy",
        "crowley_reversed": "Pride before fall",
        "numerology": 6,
        "thoth_attributes": {
            "color": "Red-gold",
            "planet": "Jupiter in Leo",
            "thelemic_key": "Energy Crowned with Victory",
        },
        "picture_reversed": "6_of_wands_reversed.jpg",
    },
    {
        "name": "Seven of Wands",
        "number": 70,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Represents perseverance, standing your ground, and defending your position.",
        "picture": "7_of_wands.jpg",
        "card": "Seven of Wands",
        "crowley_name": "Valour",
        "upright": "Challenge, competition, perseverance, defending position",
        "reversed": "Giving up, overwhelmed, yielding, lack of confidence",
        "crowley_upright": "Mars in Leo - Courage in action",
        "crowley_reversed": "Cowardice, retreat",
        "numerology": 7,
        "thoth_attributes": {
            "color": "Red-scarlet",
            "planet": "Mars in Leo",
            "thelemic_key": "The Lion's Heart",
        },
        "picture_reversed": "7_of_wands_reversed.jpg",
    },
    {
        "name": "Eight of Wands",
        "number": 71,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Symbolizes swift action, movement, and progress.",
        "picture": "8_of_wands.jpg",
        "card": "Eight of Wands",
        "crowley_name": "Swiftness",
        "upright": "Movement, quick decisions, speed, action",
        "reversed": "Delays, frustration, resisting change, slowing down",
        "crowley_upright": "Mercury in Sagittarius - Rapid communication",
        "crowley_reversed": "Scattered thoughts, miscommunication",
        "numerology": 8,
        "thoth_attributes": {
            "color": "Yellow-red",
            "planet": "Mercury in Sagittarius",
            "thelemic_key": "The Arrows of Truth",
        },
        "picture_reversed": "8_of_wands_reversed.jpg",
    },
    {
        "name": "Nine of Wands",
        "number": 72,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Represents resilience, courage, and persistence.",
        "picture": "9_of_wands.jpg",
        "card": "Nine of Wands",
        "crowley_name": "Strength",
        "upright": "Resilience, perseverance, defensive, last stand",
        "reversed": "Exhaustion, giving up, defensiveness, struggle",
        "crowley_upright": "Moon in Sagittarius - Enduring energy",
        "crowley_reversed": "Collapse under pressure",
        "numerology": 9,
        "thoth_attributes": {
            "color": "Red-violet",
            "planet": "Moon in Sagittarius",
            "thelemic_key": "The Great Fortitude",
        },
        "picture_reversed": "9_of_wands_reversed.jpg",
    },
    {
        "name": "Ten of Wands",
        "number": 73,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Symbolizes burden, responsibility, and hard work.",
        "picture": "10_of_wands.jpg",
        "card": "Ten of Wands",
        "crowley_name": "Oppression",
        "upright": "Burden, responsibility, hard work, stress",
        "reversed": "Taking on too much, avoiding responsibility, burnout",
        "crowley_upright": "Saturn in Sagittarius - Weight of wisdom",
        "crowley_reversed": "Crushing responsibility",
        "numerology": 10,
        "thoth_attributes": {
            "color": "Black-red",
            "planet": "Saturn in Sagittarius",
            "thelemic_key": "The Burden of the Wise",
        },
        "picture_reversed": "10_of_wands_reversed.jpg",
    },
    {
        "name": "Page of Wands",
        "number": 74,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Represents enthusiasm, exploration, and new ideas.",
        "picture": "page_of_wands.jpg",
        "card": "Page of Wands",
        "crowley_name": "The Princess of the Shining Flame",
        "upright": "Enthusiasm, exploration, discovery, free spirit",
        "reversed": "Lack of direction, procrastination, insecurity",
        "crowley_upright": "Earth of Fire - Spark of inspiration",
        "crowley_reversed": "Unfocused energy",
        "numerology": None,
        "thoth_attributes": {
            "element": "Earth of Fire",
            "thelemic_key": "The Phoenix Energy",
        },
        "picture_reversed": "page_of_wands_reversed.jpg",
    },
    {
        "name": "Knight of Wands",
        "number": 75,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Symbolizes adventure, passion, and impulsiveness.",
        "picture": "knight_of_wands.jpg",
        "card": "Knight of Wands",
        "crowley_name": "The Lord of the Flame and the Lightning",
        "upright": "Energy, passion, adventure, impulsiveness",
        "reversed": "Haste, scattered energy, delays, frustration",
        "crowley_upright": "Fire of Fire - Pure energy",
        "crowley_reversed": "Destructive fire",
        "numerology": None,
        "thoth_attributes": {
            "element": "Fire of Fire",
            "thelemic_key": "The Thunderbolt",
        },
        "picture_reversed": "knight_of_wands_reversed.jpg",
    },
    {
        "name": "Queen of Wands",
        "number": 76,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Represents confidence, independence, and charisma.",
        "picture": "queen_of_wands.jpg",
        "card": "Queen of Wands",
        "crowley_name": "The Queen of the Thrones of Flame",
        "upright": "Confidence, independence, vibrancy, determination",
        "reversed": "Insecurity, jealousy, dependence, selfishness",
        "crowley_upright": "Water of Fire - Controlled passion",
        "crowley_reversed": "Emotional volatility",
        "numerology": None,
        "thoth_attributes": {
            "element": "Water of Fire",
            "thelemic_key": "The Solar Feminine",
        },
        "picture_reversed": "queen_of_wands_reversed.jpg",
    },
    {
        "name": "King of Wands",
        "number": 77,
        "arcana": "Minor",
        "suit": "Wands",
        "description": "Symbolizes leadership, vision, and boldness.",
        "picture": "king_of_wands.jpg",
        "card": "King of Wands",
        "crowley_name": "The Prince of the Chariot of Fire",
        "upright": "Leadership, vision, big picture, taking control",
        "reversed": "Impulsiveness, ruthlessness, dominating, poor leadership",
        "crowley_upright": "Air of Fire - Willpower directed",
        "crowley_reversed": "Tyrannical will",
        "numerology": None,
        "thoth_attributes": {
            "element": "Air of Fire",
            "thelemic_key": "The Fiery Intellect",
        },
        "picture_reversed": "king_of_wands_reversed.jpg",
    },
]
